RAW_PATH = "./data/raw/"
PROCESSED_PATH = "./data/processed/"
CHECKPOINTS_PATH = "./checkpoints/train_models/"
IMAGES_PATH = "./outputs/train_images/"
TEST_IMAGE_PATH = "./outputs/test_images/"
BEST_MODEL_PATH = "./checkpoints/best_model/"
